services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    image: ubuntu-bind
    container_name: dns
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - asa-network

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy-nginx
    container_name: proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - webmail
    networks:
      - asa-network

  webmail:
    build:
      context: ./webmail
      dockerfile: Dockerfile
    image: rainloop-webmail
    container_name: webmail
    restart: always
    networks:
      - asa-network
    volumes:
      - webmail-data:/var/www/html/rainloop/data

  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    image: postfix-dovecot
    container_name: email
    restart: always
    ports:
      - "25:25/tcp"    # SMTP
      - "587:587/tcp"  # SMTP (submission)
      - "110:110/tcp"  # POP3
      - "143:143/tcp"  # IMAP
    networks:
      - asa-network

networks:
  asa-network:
    driver: bridge

volumes:
  webmail-data: